services:
  db:
    image: postgres:17.6-alpine
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=catalog_db
    networks:
      - academy_manager
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./posgresql/init_shadow_db.sql:/docker-entrypoint-initdb.d/init_shadow_db.sql

networks:
  academy_manager:
    external: true
    name: catalog_graphql_api_example_network

volumes:
  db:
    driver: local
